# Generated by Django 6.0.7 on 2026-08-31 13:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa konta / portfela')),
                ('account_type', models.CharField(choices=[('checking', 'Konto osobiste (ROR)'), ('savings', 'Konto oszczędnościowe'), ('cash', 'Gotówka / Portfel'), ('card', 'Karta kredytowa'), ('investment', 'Inwestycje / Lokata'), ('other', 'Inne')], default='checking', max_length=20, verbose_name='Typ konta')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Saldo początkowe (PLN)')),
                ('currency', models.CharField(default='PLN', max_length=10, verbose_name='Waluta')),
                ('icon', models.CharField(default='bi-wallet2', max_length=50, verbose_name='Ikona Bootstrap / Emoji')),
                ('color', models.CharField(default='#0284c7', max_length=30, verbose_name='Kolor akcentu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Konto aktywne')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
            ],
            options={
                'verbose_name': 'Konto / Portfel',
                'verbose_name_plural': 'Konta i Portfele',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa kategorii')),
                ('category_type', models.CharField(choices=[('expense', 'Wydatek'), ('income', 'Przychód')], default='expense', max_length=10, verbose_name='Typ kategorii')),
                ('icon', models.CharField(default='bi-tag', max_length=50, verbose_name='Ikona (Bootstrap lub Emoji)')),
                ('color', models.CharField(default='#3b82f6', max_length=30, verbose_name='Kolor kafelka')),
                ('is_default', models.BooleanField(default=False, verbose_name='Kategoria systemowa')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ['category_type', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nazwa opłaty / Abonament')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kwota (PLN)')),
                ('frequency', models.CharField(choices=[('monthly', 'Miesięcznie'), ('quarterly', 'Kwartalnie'), ('yearly', 'Rocznie')], default='monthly', max_length=20, verbose_name='Częstotliwość')),
                ('due_day', models.IntegerField(default=1, verbose_name='Dzień płatności (1-31)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywna płatność')),
                ('last_paid_date', models.DateField(blank=True, null=True, verbose_name='Data ostatniej opłaty')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notatki / Numer umowy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.account', verbose_name='Domyślne konto płatności')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category', verbose_name='Kategoria')),
            ],
            options={
                'verbose_name': 'Płatność cykliczna',
                'verbose_name_plural': 'Płatności cykliczne',
                'ordering': ['due_day', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Rok')),
                ('month', models.IntegerField(verbose_name='Miesiąc (1-12)')),
                ('amount_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Limit budżetowy (PLN)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_budgets', to='budget.category', verbose_name='Kategoria wydatków')),
            ],
            options={
                'verbose_name': 'Limit budżetowy',
                'verbose_name_plural': 'Limity budżetowe',
                'ordering': ['-year', '-month', 'category__name'],
                'unique_together': {('category', 'year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', 'Wydatek'), ('income', 'Przychód'), ('transfer', 'Przelew między kontami')], default='expense', max_length=10, verbose_name='Typ transakcji')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kwota (PLN)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data transakcji')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł / Odbiorca / Opis')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Dodatkowe notatki')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='budget/receipts/', verbose_name='Zdjęcie paragonu / faktury')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='budget.account', verbose_name='Konto źródłowe')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.category', verbose_name='Kategoria')),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='budget.account', verbose_name='Konto docelowe (dla przelewów)')),
            ],
            options={
                'verbose_name': 'Transakcja',
                'verbose_name_plural': 'Transakcje',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date'], name='budget_tran_date_dd1bca_idx'), models.Index(fields=['transaction_type', '-date'], name='budget_tran_transac_b6a14d_idx'), models.Index(fields=['account', '-date'], name='budget_tran_account_ca4b48_idx'), models.Index(fields=['category', '-date'], name='budget_tran_categor_e8d13d_idx')],
            },
        ),
    ]
