# Generated by Django 6.0.7 on 2026-08-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['owner', '-is_active', 'name'], 'verbose_name': 'Konto / Portfel', 'verbose_name_plural': 'Konta i Portfele'},
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.CharField(choices=[('personal', '👤 Moje prywatne (Jakub)'), ('business', '💼 Moje firmowe (B2B / Działalność)'), ('partner', '👩\u200d🦰 Konto partnerki'), ('joint', '👥 Wspólne domowe')], default='personal', max_length=20, verbose_name='Właściciel / Profil'),
        ),
    ]
