# Generated by Django 6.0.7 on 2026-08-31 14:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_seed_default_accounts_and_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='recurringpayment',
            options={'ordering': ['due_day', 'title'], 'verbose_name': 'Płatność cykliczna / Zobowiązanie', 'verbose_name_plural': 'Płatności cykliczne i Zobowiązania'},
        ),
        migrations.AddField(
            model_name='category',
            name='default_budget_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Domyślny stały limit miesięczny (PLN)'),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia / ostatniej raty (opcjonalnie)'),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data rozpoczęcia'),
        ),
        migrations.AddField(
            model_name='recurringpayment',
            name='total_installments',
            field=models.IntegerField(blank=True, null=True, verbose_name='Całkowita liczba rat (opcjonalnie)'),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kwota raty / opłaty (PLN)'),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notatki / Numer umowy / Kredyt'),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Nazwa opłaty / Zobowiązanie / Rata'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='destination_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='budget.account', verbose_name='Konto docelowe (tylko dla przelewów)'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notatki / Szczegóły'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='budget/receipts/%Y/%m/', verbose_name='Zdjęcie paragonu / Faktura'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Tytuł / Opis transakcji'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ostatnia zmiana'),
        ),
    ]
