# Generated by Django 6.0.7 on 2026-08-31 16:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_alter_category_default_budget_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nazwa planowanego zakupu (np. Sofa, Telewizor, Buty)')),
                ('estimated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Orientacyjna cena (PLN)')),
                ('target_date', models.DateField(blank=True, null=True, verbose_name='Planowany termin zakupu (opcjonalnie)')),
                ('priority', models.CharField(choices=[('low', '🟢 Niski'), ('medium', '🟡 Średni'), ('high', '🔴 Wysoki / Pilny')], default='medium', max_length=20, verbose_name='Priorytet')),
                ('status', models.CharField(choices=[('planned', 'Do kupienia'), ('purchased', 'Kupione / Zrealizowane'), ('cancelled', 'Anulowane')], default='planned', max_length=20, verbose_name='Status')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do oferty / sklepu / Ceneo')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notatki / Wymiary / Sklep')),
                ('saved_amount', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Zaoszczędzono na ten cel (PLN)')),
                ('purchased_date', models.DateField(blank=True, null=True, verbose_name='Data realizacji zakupu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category', verbose_name='Kategoria')),
                ('target_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.account', verbose_name='Docelowe konto / Źródło')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_expenses', to='budget.transaction', verbose_name='Powiązana transakcja wydatku')),
            ],
            options={
                'verbose_name': 'Planowany wydatek / Cel zakupowy',
                'verbose_name_plural': 'Planowane wydatki i Cele',
                'ordering': ['status', '-priority', 'target_date', '-created_at'],
            },
        ),
    ]
