# Generated by Django 6.0.7 on 2026-08-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_plannedexpense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedexpense',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', '🟢 Niski'), ('medium', '🟡 Średni'), ('high', '🔴 Wysoki / Pilny')], default='medium', max_length=20, verbose_name='Priorytet'),
        ),
        migrations.AlterField(
            model_name='plannedexpense',
            name='status',
            field=models.CharField(blank=True, choices=[('planned', 'Do kupienia'), ('purchased', 'Kupione / Zrealizowane'), ('cancelled', 'Anulowane')], default='planned', max_length=20, verbose_name='Status'),
        ),
    ]
