# Generated by Django 6.0.7 on 2026-08-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_portfolio', '0004_market_publisher_address_publisher_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['title'], 'verbose_name': 'Gra', 'verbose_name_plural': 'Gry'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Gatunek gry', 'verbose_name_plural': 'Gatunki gier'},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={'ordering': ['name'], 'verbose_name': 'Rynek giełdowy', 'verbose_name_plural': 'Rynki giełdowe'},
        ),
        migrations.AlterModelOptions(
            name='platform',
            options={'ordering': ['name'], 'verbose_name': 'Platforma sprzętowa', 'verbose_name_plural': 'Platformy sprzętowe'},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'ordering': ['name'], 'verbose_name': 'Wydawca', 'verbose_name_plural': 'Wydawcy'},
        ),
        migrations.AlterModelOptions(
            name='stockmetric',
            options={'ordering': ['-date'], 'verbose_name': 'Metryka giełdowa', 'verbose_name_plural': 'Metryki giełdowe'},
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.IntegerField(unique=True, verbose_name='ID gry w hurtowni'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='da_portfolio.genre', verbose_name='Gatunki'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(related_name='games', to='da_portfolio.platform', verbose_name='Platformy'),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='da_portfolio.publisher', verbose_name='Wydawca'),
        ),
        migrations.AlterField(
            model_name='game',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ocena'),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data premiery'),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Tytuł gry'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Gatunek gry'),
        ),
        migrations.AlterField(
            model_name='market',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Rynek giełdowy'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Platforma sprzętowa'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kraj'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishers', to='da_portfolio.market', verbose_name='Rynek'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Wydawca / Spółka'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='ticker',
            field=models.CharField(max_length=20, unique=True, verbose_name='Symbol giełdowy (Ticker)'),
        ),
        migrations.AlterField(
            model_name='stockmetric',
            name='date',
            field=models.DateField(verbose_name='Data notowania'),
        ),
        migrations.AlterField(
            model_name='stockmetric',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Kapitalizacja rynkowa'),
        ),
        migrations.AlterField(
            model_name='stockmetric',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_metrics', to='da_portfolio.publisher', verbose_name='Wydawca'),
        ),
        migrations.AlterField(
            model_name='stockmetric',
            name='stock_close',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Kurs zamknięcia'),
        ),
        migrations.AlterField(
            model_name='stockmetric',
            name='volume',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Wolumen'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['title'], name='da_portfoli_title_d35e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['rating'], name='da_portfoli_rating_2e0a06_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['release_date'], name='da_portfoli_release_a0beee_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['publisher', '-rating'], name='da_portfoli_publish_2b40ce_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['name'], name='da_portfoli_name_91e38f_idx'),
        ),
        migrations.AddIndex(
            model_name='publisher',
            index=models.Index(fields=['ticker'], name='da_portfoli_ticker_618c86_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmetric',
            index=models.Index(fields=['publisher', 'date'], name='da_portfoli_publish_b4ad0e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmetric',
            index=models.Index(fields=['date'], name='da_portfoli_date_134bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmetric',
            index=models.Index(fields=['publisher', '-date'], name='da_portfoli_publish_0779c7_idx'),
        ),
    ]
