# Generated by Django 6.0.7 on 2026-08-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
