# Generated by Django 6.0.7 on 2026-08-10 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_experience_end_date_experience_start_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa albumu (Kategoria)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Krótki opis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/photos/', verbose_name='Zdjęcie')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tytuł / Podpis')),
                ('camera', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aparat')),
                ('focal_length', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ogniskowa')),
                ('iso', models.CharField(blank=True, max_length=50, null=True, verbose_name='ISO')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='portfolio.album')),
            ],
        ),
    ]
