# Generated by Django 6.0.7 on 2026-08-15 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_album_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['name'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albumy'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Doświadczenie zawodowe', 'verbose_name_plural': 'Doświadczenia zawodowe'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Zdjęcie', 'verbose_name_plural': 'Zdjęcia'},
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='company',
            field=models.CharField(max_length=150, verbose_name='Firma / Organizacja'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(verbose_name='Opis obowiązków i osiągnięć'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='job_title',
            field=models.CharField(max_length=150, verbose_name='Stanowisko'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(default='2024-01-01', verbose_name='Data rozpoczęcia'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='portfolio.album', verbose_name='Album'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['-start_date'], name='portfolio_e_start_d_79f850_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['album', '-uploaded_at'], name='portfolio_p_album_i_8367b5_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-uploaded_at'], name='portfolio_p_uploade_27122e_idx'),
        ),
    ]
