# Generated by Django 6.0.8 on 2026-08-28 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_album_options_alter_experience_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nazwa certyfikatu / Kursu')),
                ('issuer', models.CharField(max_length=150, verbose_name='Wydawca / Organizacja')),
                ('year', models.CharField(max_length=50, verbose_name='Data / Rok')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Certyfikat',
                'verbose_name_plural': 'Certyfikaty',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CVProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Jakub', max_length=150, verbose_name='Imię i nazwisko')),
                ('title', models.CharField(default='Specjalista ds. Danych / Programista', max_length=150, verbose_name='Tytuł zawodowy')),
                ('summary', models.TextField(blank=True, default='Pasjonat technologii, automatyzacji procesów i analizy danych z wieloletnim doświadczeniem w tworzeniu dedykowanych systemów i zarządzaniu bazami danych.', verbose_name='Podsumowanie zawodowe (Bio)')),
                ('email', models.CharField(blank=True, default='', max_length=100, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='Telefon')),
                ('location', models.CharField(blank=True, default='Polska', max_length=100, verbose_name='Lokalizacja')),
                ('linkedin', models.CharField(blank=True, default='', max_length=200, verbose_name='LinkedIn URL')),
                ('github', models.CharField(blank=True, default='', max_length=200, verbose_name='GitHub URL')),
                ('website', models.CharField(blank=True, default='', max_length=200, verbose_name='Strona WWW')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='portfolio/avatars/', verbose_name='Zdjęcie profilowe')),
            ],
            options={
                'verbose_name': 'Profil CV',
                'verbose_name_plural': 'Profile CV',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=200, verbose_name='Uczelnia / Szkoła')),
                ('degree', models.CharField(max_length=150, verbose_name='Tytuł / Stopień')),
                ('field_of_study', models.CharField(max_length=150, verbose_name='Kierunek / Specjalizacja')),
                ('years', models.CharField(max_length=50, verbose_name='Lata nauki (np. 2019 - 2023)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Opis / Osiągnięcia')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Edukacja',
                'verbose_name_plural': 'Edukacja',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Język')),
                ('level', models.CharField(default='B2', max_length=100, verbose_name='Poziom biegłości')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Język obcy',
                'verbose_name_plural': 'Języki obce',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='Umiejętności techniczne', max_length=100, verbose_name='Kategoria')),
                ('name', models.CharField(max_length=100, verbose_name='Umiejętność / Narzędzie')),
                ('level', models.IntegerField(default=5, verbose_name='Poziom (1-5)')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Umiejętność',
                'verbose_name_plural': 'Umiejętności',
                'ordering': ['order', 'category', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['order', '-id'], 'verbose_name': 'Doświadczenie zawodowe', 'verbose_name_plural': 'Doświadczenia zawodowe'},
        ),
        migrations.RemoveIndex(
            model_name='experience',
            name='portfolio_e_start_d_79f850_idx',
        ),
        migrations.AddField(
            model_name='experience',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Aktualne stanowisko'),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Lokalizacja / Tryb'),
        ),
        migrations.AddField(
            model_name='experience',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Kolejność'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.CharField(blank=True, default='Obecnie', max_length=50, verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.CharField(default='2023', max_length=50, verbose_name='Data rozpoczęcia (np. 01.2023)'),
        ),
    ]
