# Generated by Django 6.0.8 on 2026-08-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_certificate_cvprofile_education_language_skill_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-is_current', '-start_date', '-id'], 'verbose_name': 'Doświadczenie zawodowe', 'verbose_name_plural': 'Doświadczenia zawodowe'},
        ),
        migrations.AlterField(
            model_name='experience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data zakończenia'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data rozpoczęcia'),
        ),
    ]
