# Generated by Django 6.0.8 on 2026-08-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_experience_options_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa hobby / Zainteresowania')),
                ('icon', models.CharField(blank=True, default='🎮', max_length=50, verbose_name='Ikona / Emoji')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Hobby',
                'verbose_name_plural': 'Hobby i Zainteresowania',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Nazwa projektu')),
                ('role', models.CharField(blank=True, default='', max_length=150, verbose_name='Rola / Stanowisko w projekcie')),
                ('technologies', models.CharField(blank=True, default='', max_length=255, verbose_name='Technologie (po przecinku)')),
                ('url', models.CharField(blank=True, default='', max_length=255, verbose_name='Link do projektu / GitHub')),
                ('description', models.TextField(blank=True, default='', verbose_name='Opis projektu i osiągniętych rezultatów')),
                ('order', models.IntegerField(default=0, verbose_name='Kolejność')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekty',
                'ordering': ['order', '-id'],
            },
        ),
    ]
