# Generated by Django 6.0.7 on 2026-08-30 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_hobby_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['sort_order', '-uploaded_at'], 'verbose_name': 'Zdjęcie', 'verbose_name_plural': 'Zdjęcia'},
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='portfolio_p_album_i_8367b5_idx',
        ),
        migrations.AddField(
            model_name='album',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover_for_albums', to='portfolio.photo', verbose_name='Zdjęcie okładki'),
        ),
        migrations.AddField(
            model_name='photo',
            name='aperture',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Przysłona'),
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Opis / Historia zdjęcia'),
        ),
        migrations.AddField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Wyróżnione (na stronie głównej)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='lens',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Obiektyw'),
        ),
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Miejsce wykonania'),
        ),
        migrations.AddField(
            model_name='photo',
            name='shutter_speed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Czas naświetlania'),
        ),
        migrations.AddField(
            model_name='photo',
            name='sort_order',
            field=models.IntegerField(default=0, verbose_name='Kolejność w albumie'),
        ),
        migrations.AddField(
            model_name='photo',
            name='tags',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tagi (oddzielone przecinkami)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='taken_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data wykonania'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['album', 'sort_order', '-uploaded_at'], name='portfolio_p_album_i_574c48_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['is_featured'], name='portfolio_p_is_feat_ab7e09_idx'),
        ),
    ]
